CREATE TABLE MEMBER (
	MEMBER_NO NUMBER NOT NULL,
	MEMBER_ID	varchar2(20) CONSTRAINT NN_MEMBER_ID NOT NULL,
	MEMBER_PW	varchar2(20) CONSTRAINT NN_MEMBER_PW NOT NULL,
	MEMBER_NAME	varchar2(20) CONSTRAINT NN_MEMBER_NAME NOT NULL,
	MEMBER_BIRTH_DATE DATE CONSTRAINT NN_MEMBER_BIRTH_DATE NOT NULL,
	MEMBER_EMAIL	varchar2(20) CONSTRAINT NN_MEMBER_EMAIL NOT NULL,
	MEMBER_ADDRESS	varchar2(50) CONSTRAINT NN_MEMBER_ADDRESS NOT NULL,
	MEMBER_PHONE	NUMBER CONSTRAINT NN_MEMBER_PHONE NOT NULL,
	MEMBER_DEL_YN	varchar2(3) DEFAULT 'N',
	MEMBER_DEL_DATE	DATE,
	MEMBER_ENROLL_DATE	DATE DEFAULT SYSDATE,
	MEMBER_LIKE_TYPE	varchar2(20),
	MEMBER_LIKE_SIZE	varchar2(20),
	MEMBER_LIKE_COLOR	varchar2(20),
	MEMBER_LIKE_CHAR	varchar2(20)
);

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	MEMBER_NO
);

CREATE TABLE ANIMAL (
	ANI_NO	NUMBER CONSTRAINT NN_ANI_NO NOT NULL,
	ANI_NAME varchar2(20) CONSTRAINT NN_ANI_NAME NOT NULL,
	ANI_TYPE varchar2(20) CONSTRAINT NN_ANI_TYPE NOT NULL CONSTRAINT CK_ANI_TYPE CHECK (ANI_TYPE IN ('강아지', '고양이')),
	ANI_KIND varchar2(20) CONSTRAINT NN_ANI_KIND NOT NULL,
	ANI_GENDER varchar2(20)	CONSTRAINT NN_ANI_GENDER NOT NULL,
	ANI_AGE	NUMBER CONSTRAINT NN_ANI_AGE NOT NULL,
	ANI_NEU_YN	varchar2(3)	CONSTRAINT NN_ANI_NEU_YN NOT NULL,
	ANI_ADOPT_YN varchar2(3) CONSTRAINT NN_ANI_ADOPT_YN NOT NULL,
	ANI_SIZE varchar2(20) CONSTRAINT NN_ANI_SIZE NOT NULL CONSTRAINT CK_ANI_SIZE CHECK (ANI_SIZE IN ('대형', '중형', '소형')),
	ANI_COLOR varchar2(20) CONSTRAINT NN_ANI_COLOR NOT NULL CONSTRAINT CK_ANI_COLOR CHECK(ANI_COLOR IN ('검정색', '회색', '흰색', '갈색', '나머지색')),
	ANI_CHAR varchar2(50) CONSTRAINT NN_ANI_CHAR NOT NULL CONSTRAINT CK_ANI_CHAR CHECK(ANI_CHAR IN ('자신감뿜뿜', '부끄럼쟁이', '독립적', '활발함', '높은적응력')),
	ANI_SPECIAL	varchar2(200) CONSTRAINT NN_ANI_SPECIAL NOT NULL
);


ALTER TABLE ANIMAL ADD CONSTRAINT PK_ANIMAL PRIMARY KEY (
	ANI_NO
);
